---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

verifier:
  name: inspec

platforms:
  - name: debian-8.2
    run_list:
      - recipe[apt]
      - recipe[git]

suites:
  - name: default
    run_list:
      - recipe[elite]
      - recipe[elite::dotfiles]
      - recipe[elite::ack]
      - recipe[elite::bash]
      - recipe[elite::cask]
      - recipe[elite::emacs]
      - recipe[elite::git]
      - recipe[elite::packages]
      - recipe[elite::pics]
      - recipe[elite::stuff]
      - recipe[elite::terminfo]
      - recipe[elite::tmux]
      - recipe[elite::x]
      - recipe[elite::zsh]
      - recipe[elite::slim]
      - recipe[elite::dunst]
      - recipe[elite::dzen2]
      - recipe[elite::conky]
      - recipe[elite::conky_dzen2]
      - recipe[elite::stumpwm]
      - recipe[elite::gtk]
    attributes:
      elite:
        users: [root, h4x0r]
        groups: [elite]
        packages: [tcpdump, emacs-nox]
        slim:
          user: h4x0r
          session: stumpwm
        root:
          home: /root
          group: root
          bash: {}
        h4x0r:
          home: /home/h4x0r
          dotfd: /home/h4x0r/.dotfiles
          group: elite
          shell: /bin/zsh
          groups: [elite]
          password: $1$ZqEOrqH1$Xdlls.mpHmHcP4XsQl9Ah.
          ack: {}
          cask: {}
          emacs: {}
          git: {}
          stuff:
            install_path: /home/h4x0r/stuff
          terminfo: {}
          x: {}
          tmux:
            scripts:
              test:
                path: /tmp/tmux-test
                workdir: /tmp
                default_window: "0"
                windows:
                  "0":
                    name: kitchen
                    win:
                      "0": split-window -h {TARGET}
                      "1": select-pane {TARGET}0
                    cmds:
                      "0": htop
                      "1": nload
          zsh: {}
          pics:
            pics: [thc.jpg, defcon-green.jpg]
          conky: {}
          dunst: {}
          stumpwm: {}
          gtk: {}
