---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

verifier:
  name: inspec

provisioner:
  name: chef_zero
  require_chef_omnibus: 12

platforms:
  - name: debian-9.0
    run_list:
      - recipe[apt]
      - recipe[git]
  - name: ubuntu-16.04
    run_list:
      - recipe[apt]
      - recipe[git]

suites:
  - name: default
    run_list:
      - recipe[elite]
      - recipe[elite::packages]
      - recipe[elite::dotfiles]
      - recipe[elite::ack]
      - recipe[elite::bin]
      - recipe[elite::bash]
      - recipe[elite::cask]
      - recipe[elite::emacs]
      - recipe[elite::git]
      - recipe[elite::pics]
      - recipe[elite::stuff]
      - recipe[elite::terminfo]
      - recipe[elite::tmux]
      - recipe[elite::x]
      - recipe[elite::zsh]
      - recipe[elite::slim]
      - recipe[elite::dunst]
      - recipe[elite::dzen2]
      - recipe[elite::conky]
      - recipe[elite::conky_dzen2]
      - recipe[elite::stumpwm]
      - recipe[elite::gtk]
      - recipe[elite::chef]
      - recipe[elite::irssi]
      - recipe[elite::rofi]
      - recipe[elite::docker_host]
      - recipe[elite::pentestenv]
      - recipe[elite::python]

    attributes:
      elite:
        users: [root, h4x0r]
        groups: [elite]
        packages: [tcpdump, emacs-nox]
        slim:
          user: h4x0r
          session: stumpwm
        docker_host:
          users: [h4x0r]
        python:
          "2": {}
          "3":
            options:
              package_name: python3
              dev_package: python3-dev
            packages:
              - PyYaML
        root:
          home: /root
          group: root
          bash: {}
        h4x0r:
          home: /home/h4x0r
          dotfd: /home/h4x0r/.dotfiles
          group: elite
          shell: /bin/zsh
          groups: [elite]
          password: $1$ZqEOrqH1$Xdlls.mpHmHcP4XsQl9Ah.
          ack: {}
          bin: {}
          cask: {}
          dotfiles:
            init_repo: true
          emacs:
            repository: https://github.com/Sliim/emacs.d
            apps_repository: https://github.com/Sliim/emacs-apps
            apps_dependencies: [magit]
            apps:
              dired:
                desktop:
                  Name: dired
              magit:
                desktop:
                  Name: Magit
          git: {}
          rofi: {}
          stuff:
            install_path: /home/h4x0r/stuff
          terminfo: {}
          x: {}
          tmux:
            scripts:
              test:
                path: /tmp/tmux-test
                workdir: /tmp
                default_window: "0"
                windows:
                  "0":
                    name: kitchen
                    win:
                      "0": split-window -h {TARGET}
                      "1": select-pane {TARGET}0
                    cmds:
                      "0": htop
                      "1": nload
          zsh: {}
          pentestenv:
            config:
              instance: [kali]
              targets: [mrrobot]
              kali:
                vbox:
                  customize:
                    memory: 1024
          pics:
            pics: [thc.jpg, defcon-green.jpg]
          conky: {}
          dunst: {}
          stumpwm:
            contrib: true
            modules:
              elite:
                - keyring
                - autosplit
          gtk: {}
          chef:
            node_name: sliim
            client_key_path: /tmp/my-key
            chef_server_url: http:localhost:1337
          irssi:
            settings:
                core:
                  real_name: elite
                  user_name: elite
                  nick: elite
            chatnets: [ccc]
            servers:
              -
                address: irc.hackint.eu
                chatnet: ccc
                port: 9999
                use_ssl: yes
                ssl_verify: no
                autoconnect: yes
            channels:
              -
                name: "#elite-cookbook"
                chatnet: ccc
                autojoin: yes
